#!/bin/sh

# Cleans up after the auxiliary files that were created when installing
# the autodiffadolc package (shamelessly taken from the XML source pkg)
#
echo "  Cleaning up after installing the autodiffadolc package"

## No configure currently --> empty for now: not yet really needed

cd src/ADOLC
make purge
cd ../../

for f in config.log config.status config.cache ; do
  if test -w $f ; then
    rm -f $f
  fi
done

for f in src/Makevars src/*.o src/*.so ; do
  if test -w $f ; then
    rm -f $f
  fi
done


